### ISSUE TITLE
提交项目:SweetTips

### ISSUE THREAD

**Issue by HuanHaiLiuXin** [opendigg/opendigg-share-projects#7]
项目名称:
SweetTips (https://github.com/HuanHaiLiuXin/SweetTips)
子标题: 
SweetTips:快意灵动的提示库,自定义Toast,Snackbar,一行代码搞定多重属性设置!
相关介绍:
**Android原生Toast及Design包中的Snackbar，实现一些常见需求比较繁琐，比如Toast自定义显示时间，Toast及Snackbar自定义出入场动画，Toast无需等待即时显示等**
使用SweetTips可以轻松的解决以上问题！

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/sweettips
