### ISSUE TITLE
提交项目

### ISSUE THREAD

**Issue by youlookwhat** [opendigg/opendigg-share-projects#8]
项目名称：CloudReader
子标题：使用MVVM-DataBinding开发的仿网易云音乐UI的阅读客户端
相关介绍：一款基于网易云音乐UI，使用Gank.Io及豆瓣api开发的符合Google Material Design的Android开源项目。

github: https://github.com/youlookwhat/CloudReader

**Comment by opendigg** [comment]
已收录 http://www.opendigg.com/p/yunyue
